Update build-packages-new.yml

diff --git a/.github/workflows/build-packages-new.yml b/.github/workflows/build-packages-new.yml
--- a/.github/workflows/build-packages-new.yml
+++ b/.github/workflows/build-packages-new.yml
@@ -1,116 +1,54 @@
-include $(TOPDIR)/rules.mk
+name: build-packages-new
 
-PKG_NAME:=nikki
-PKG_RELEASE:=1
+on:
+  workflow_dispatch:
 
-PKG_SOURCE_PROTO:=git
-PKG_SOURCE_URL:=https://github.com/MetaCubeX/mihomo.git
-PKG_SOURCE_DATE:=2025-05-13
-PKG_SOURCE_VERSION:=266fb03838365bb5df14d7531476514427eba2e4
-PKG_MIRROR_HASH:=b17102d5ecd72fa05011eb2776500497e735225b811cdc5cd9697a6e85a953f8
+jobs:
+  build:
+    name: ${{ matrix.arch }}-${{ matrix.branch }} build
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        arch:
+          - aarch64_generic
+        branch:
+          - openwrt-24.10
 
-PKG_LICENSE:=GPL3.0+
-PKG_MAINTAINER:=***
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-PKG_BUILD_DEPENDS:=golang/host
-PKG_BUILD_PARALLEL:=1
-PKG_BUILD_FLAGS:=no-mips16
+      - name: Build package
+        uses: openwrt/gh-action-sdk@main
+        env:
+          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
+          FEEDNAME: nikki
+          PACKAGES: luci-app-nikki
+          NO_REFRESH_CHECK: true
 
-PKG_BUILD_VERSION:=v1.19.8-266fb038
-PKG_BUILD_TIME:=$(shell date -u -Iseconds)
-PKG_VERSION:=$(PKG_SOURCE_DATE)~$(PKG_BUILD_VERSION)-Mod
+      - name: Extract package version
+        id: extract_version
+        run: |
+          set -e
+          PKG_FILE=$(find bin/packages/${{ matrix.arch }}/nikki -name 'nikki_*.ipk' | head -n 1)
+          if [[ -z "$PKG_FILE" ]]; then
+            echo "❌ Package file not found!"
+            exit 1
+          fi
+          echo "Found package: $PKG_FILE"
+          VERSION=$(basename "$PKG_FILE" | sed -E 's/^nikki_([^_]+)_.*\.ipk/\1/')
+          echo "Extracted version: $VERSION"
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
-GO_PKG:=github.com/metacubex/mihomo
-GO_PKG_LDFLAGS_X:= \
-	$(GO_PKG)/constant.Version=$(PKG_BUILD_VERSION) \
-	$(GO_PKG)/constant.BuildTime=$(PKG_BUILD_TIME)
-GO_PKG_TAGS:=with_gvisor
+      - name: Compress .ipk files
+        run: |
+          mkdir -p output
+          cp bin/packages/${{ matrix.arch }}/nikki/*.ipk output/
+          zip -j Nikki-TProxy-${{ steps.extract_version.outputs.version }}_${{ matrix.arch }}-${{ matrix.branch }}.zip output/*.ipk
 
-include $(INCLUDE_DIR)/package.mk
-include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk
-
-define Package/nikki
-  SECTION:=net
-  CATEGORY:=Network
-  TITLE:=A rule based proxy in Go.
-  URL:=https://wiki.metacubex.one
-  DEPENDS:=$(GO_ARCH_DEPENDS) +ca-bundle +curl +yq firewall4 +ip-full \
-           +kmod-inet-diag +kmod-nft-socket +kmod-nft-tproxy +kmod-tun
-  PROVIDES:=nikki mihomo
-endef
-
-define Package/nikki/description
-  A rule based proxy in Go.
-endef
-
-define Package/nikki/conffiles
-/etc/config/nikki
-/etc/nikki/mixin.yaml
-/etc/nikki/nftables/reserved_ip.nft
-/etc/nikki/nftables/reserved_ip6.nft
-endef
-
-define Package/nikki/install
-	$(call GoPackage/Package/Install/Bin,$(1))
-
-	$(INSTALL_DIR) $(1)/etc/nikki \
-	               $(1)/etc/nikki/ucode \
-	               $(1)/etc/nikki/scripts \
-	               $(1)/etc/nikki/nftables \
-	               $(1)/etc/nikki/profiles \
-	               $(1)/etc/nikki/subscriptions \
-	               $(1)/etc/nikki/run \
-	               $(1)/etc/nikki/run/providers \
-	               $(1)/etc/nikki/run/providers/rule \
-	               $(1)/etc/nikki/run/providers/proxy
-
-	$(INSTALL_DATA) $(CURDIR)/files/mixin.yaml $(1)/etc/nikki/mixin.yaml
-
-	$(INSTALL_BIN) $(CURDIR)/files/ucode/include.uc $(1)/etc/nikki/ucode/include.uc
-	$(INSTALL_BIN) $(CURDIR)/files/ucode/mixin.uc $(1)/etc/nikki/ucode/mixin.uc
-	$(INSTALL_BIN) $(CURDIR)/files/ucode/hijack.ut $(1)/etc/nikki/ucode/hijack.ut
-
-	$(INSTALL_BIN) $(CURDIR)/files/scripts/include.sh $(1)/etc/nikki/scripts/include.sh
-	$(INSTALL_BIN) $(CURDIR)/files/scripts/firewall_include.sh $(1)/etc/nikki/scripts/firewall_include.sh
-	$(INSTALL_BIN) $(CURDIR)/files/scripts/debug.sh $(1)/etc/nikki/scripts/debug.sh
-
-	$(INSTALL_BIN) $(CURDIR)/files/nftables/reserved_ip.nft $(1)/etc/nikki/nftables/reserved_ip.nft
-	$(INSTALL_BIN) $(CURDIR)/files/nftables/reserved_ip6.nft $(1)/etc/nikki/nftables/reserved_ip6.nft
-
-	$(INSTALL_DIR) $(1)/etc/config
-	$(INSTALL_CONF) $(CURDIR)/files/nikki.conf $(1)/etc/config/nikki
-
-	$(INSTALL_DIR) $(1)/etc/init.d
-	$(INSTALL_BIN) $(CURDIR)/files/nikki.init $(1)/etc/init.d/nikki
-
-	$(INSTALL_DIR) $(1)/lib/upgrade/keep.d
-	$(INSTALL_DATA) $(CURDIR)/files/nikki.upgrade $(1)/lib/upgrade/keep.d/nikki
-endef
-
-define Package/nikki/postrm
-#!/bin/sh
-# Hanya dijalankan jika bukan dalam proses image build (chroot)
-if [ -z "$$IPKG_INSTROOT" ]; then
-	uci -q delete firewall.nikki
-	uci -q commit firewall
-fi
-
-rm -rf /etc/nikki
-rm -rf /www/luci-static/resources/view/nikki
-rm -rf /tmp/log/nikki
-rm -f /usr/share/luci/menu.d/luci-app-nikki.json
-rm -f /www/tinyfm/nikkifm.php
-rm -f /etc/config/nikki
-rm -f /etc/init.d/nikki
-rm -f /tmp/lock/procd_nikki.lock
-rm -f /tmp/run/nikki/profile.json
-exit 0
-endef
-
-define Build/Prepare
-	$(Build/Prepare/Default)
-	$(RM) -r $(PKG_BUILD_DIR)/rules/logic_test
-endef
-
-$(eval $(call GoBinPackage,nikki))
-$(eval $(call BuildPackage,nikki))
+      - name: Upload to artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: Nikki-TProxy-${{ steps.extract_version.outputs.version }}_${{ matrix.arch }}-${{ matrix.branch }}
+          path: Nikki-TProxy-${{ steps.extract_version.outputs.version }}_${{ matrix.arch }}-${{ matrix.branch }}.zip
